spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: TokenRelay

  eureka:
    instance:
      instance-id: ${spring.application.name}:${random.uuid}

  loadbalancer:
    ribbon:
      enabled: false

  gateway:
    routes:
      - id: product-microservice
        uri: lb://PRODUCT-MICROSERVICE
        predicates:
          - Path=/api/products/**, /api/categories/**

      - id: usuarios-microservice
        uri: lb://USUARIOS-MICROSERVICE
        predicates:
          - Path=/api/usuarios/**