spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
       - id: product-microservice
         uri: lb://PRODUCT-MICROSERVICE
         predicates:
           - Path=/api/products/**,/api/categories/**
       - id: arriving-service
         uri:
           lb://ARRIVING-MICROSERVICE
         predicates:
           - Path=/api/arriving/**
         
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}



    
              