constants:
  security:
    jwtSecret: 12345
    jwtExpirationMs: 3600
    frontEndOrigin: "http://localhost:4200"
    
  jwt:
    secretKey: 123456789
    expirationTimeInMillis: 600_000  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: product-microservice