spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lushopai/ms-apigateway.git
          clone-on-start: true

server:
  port: 8888